### ISSUE TITLE
develop plan

### ISSUE THREAD

**Issue by tfzxyinhao** [cristi993/swftools#1]
do you have some plan that how to maintain it ?

**Comment by cristi993** [comment]
Hello there :blush: 
Unfortunately no, I'll not contribute anymore on this repo :disappointed:. I modified this version of swftools just to use it for my bachelors degree project (the swfrender tool) and that was all.
If you want to contribute, feel free to fork the project :relaxed:. I can't maintain it anymore because I have to work 8 hours/day + master studies :grin:.
